chore(zero-cache): resurrect integration tests (#5546)
Refresh and resurrect zero-cache integration tests when run locally. 

They are still disabled in the CI because of a hard-to-track-down
unhandled rejection when the test pg databases are shutdown.

But until that's tracked down, the tests are still valuable to run
locally. Otherwise they rot and diverge from what will actually pass.

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
PostgresError: terminating connection due to administrator command
 ❯ ErrorResponse node_modules/postgres/src/connection.js:794:26
 ❯ handle node_modules/postgres/src/connection.js:480:6
 ❯ Socket.data node_modules/postgres/src/connection.js:315:9
 ❯ Socket.emit node:events:508:28
 ❯ addChunk node:internal/streams/readable:559:12
 ❯ readableAddChunkPushByteMode node:internal/streams/readable:510:3
 ❯ Socket.Readable.push node:internal/streams/readable:390:5
 ❯ TCP.onStreamRead node:internal/stream_base_commons:189:23
 ```