fix: Work around for initializers in ambient mode (#623)
The generated .d.ts files for `datadog` package looked something like this:

```
declare class DatadogLogSink implements LogSink {
  ...
  private _flushLock = new Lock();
```

Which gives an error in older versions of TypeScript:

```
error TS1039: Initializers are not allowed in ambient contexts.
```

By compiling the datadog package and importing the js/.d.ts pairs this problematic code is no longer present in the generated .d.ts files.