feat(zero): add support for timetz datatype (#5417)
Based on the PR https://github.com/rocicorp/mono/pull/4671 adding
support for `time` datatype, this adds the `timetz` datatype.
Interestingly, everything to do so was already in place (like the
[timetz
type](https://github.com/rocicorp/mono/blob/main/packages/zero-cache/src/types/pg-types.ts#L51)),
so we only have to slightly extend existing logic.

You can find information about the pg types in postgres' [datatype-date
doc](https://www.postgresql.org/docs/current/datatype-datetime.html).

Tests were added to test the new behavior.

Note: `time` is actually `time without timezone` and therefore adding
this would only adding the correct mapping. Hence the added code is
mainly related to support `timezone`s and is similar to the code that is
in place for `timestamp with timezone`.

Edit:
I tested this PR in our application test setup and with our application
now as well. I was previously facing the error:
```
 Error: Schema incompatibility detected between your zero schema definition and the database:
  - Type mismatch for column "time" in table "<mytable>": time without time zone is currently unsupported in Zero. Please file a bug at https://bugs.rocicorp.dev/
Please update your schema definition to match the database or migrate your database to match the schema.
```
This PR solves our problems (test passes with it and ui works) and
removes a blocker for us. The outcome is as expected.
| postgres | app ui |
| ------------- | --------- |
| <img width="714" height="326" alt="image"
src="https://github.com/user-attachments/assets/89babd31-559f-4d86-a693-7dcf8d134ce8"
/> | <img width="1008" height="150" alt="image"
src="https://github.com/user-attachments/assets/d2b16abd-fd0b-447f-9ed7-c43bade68661"
/> |

---------

Signed-off-by: GRBurst <GRBurst@protonmail.com>
Co-authored-by: Erik Arvidsson <arv@roci.dev>