Revert "feat: Print version on startup (#49)" (#51)
This reverts commit e32368a7544dcfaeb84c9310d8a0c21493359b7c.

Revert due to test breakage.

```
 FAIL  src/server/server.test.ts
  ● Test suite failed to run

    SyntaxError: Unexpected identifier

      at Runtime.loadEsmModule (node_modules/jest-runtime/build/index.js:654:24)
          at async Promise.all (index 2)
```